[package]
name = "httpaudioplayer"
version = "0.1.0"
authors = ["ksb <ksb@fluffware.se>"]

[dependencies]
hyper = "0.11"
futures = "0.1.14"
mime = "0.3"
nom= "3.2.0"
portaudio = "0.7.0"
hound = "3.1.0"